/* Floussi landing — trilingual copy (en / fr / darija).
   Kept separate from the app i18n dictionaries: marketing copy has its own
   voice, but still follows the account language + RTL direction. */

export type LandingLang = 'en' | 'fr' | 'ary'

export const landingCopy = {
  en: {
    navProduct: 'Product',
    navIq: 'Floussi IQ',
    navCoach: 'AI Coach',
    navPrivacy: 'Privacy',
    openApp: 'Open FLOUSSI',
    badge: 'AI Financial Coach · Morocco',
    h1a: 'Understand your money.',
    h1b: 'Make better decisions.',
    sub: 'FLOUSSI brings your transactions together, analyzes how you spend and turns it into clear guidance — with an AI coach that speaks Darija, French and English.',
    ctaPrimary: 'Try FLOUSSI',
    ctaSecondary: 'See the product',
    liveLabel: 'Live from your account',
    prevToday: 'Spent today',
    prevWeek: 'This week',
    prevMonth: 'This month',
    prevRecent: 'Recent transactions',
    prevScore: 'Floussi IQ',
    statTx: 'transactions tracked',
    statIq: 'financial intelligence',
    statLang: 'languages, RTL native',
    statMAD: 'local currency (MAD)',
    featTitle: 'Everything your money does, in one place',
    featSub: 'Built for how Morocco actually spends — cash, souk, family, fixed bills.',
    feat1t: 'Transactions, effortlessly',
    feat1d: 'Log an expense in seconds. Search in natural language — "tnine 11 decembre", "khobze", "50 dh" — in any of the three languages.',
    feat2t: 'Analytics that explain',
    feat2d: 'Where your money goes, necessary vs avoidable, weekend habits, trends from 14 days to a full year.',
    feat3t: 'Budgets & goals',
    feat3d: 'Monthly limits per category with smart warnings, and savings goals with real progress.',
    feat4t: 'Notifications that matter',
    feat4d: 'Budget alerts, unusual spending, weekly recaps — generated from your real data, not templates.',
    feat5t: 'Floussi IQ',
    feat5d: 'A proprietary 0–100 score of your financial health, with the exact factors behind it.',
    feat6t: 'Installable & offline-ready',
    feat6d: 'A real PWA: add it to your home screen, your data syncs to your own cloud.',
    iqTitle: 'A financial score you can actually trust',
    iqSub: 'Floussi IQ reads your real behavior — pace, essentials, weekend pattern, streaks — and explains every point.',
    iqWhy: 'What moves the score',
    iqCta: 'Open Floussi IQ',
    coachTitle: 'An AI coach that knows your numbers',
    coachSub: 'Ask in plain words — Darija, French or English. Answers are computed from your real transactions, never invented.',
    coachQ: 'Where did I spend the most this month?',
    coachA1: 'Your biggest category this month is',
    coachA2: 'that’s {pct}% of your spending. Weekly pace is on track — trimming it a little would save about',
    coachA3: 'this month.',
    coachPerMonth: '/ month',
    triTitle: 'Three languages. One native RTL.',
    triSub: 'Not a mirrored afterthought — Darija is designed first-class: layout, charts, forms and numbers all flip properly.',
    triEn: 'English',
    triFr: 'Français',
    triAry: 'الدارجة',
    privTitle: 'Your data stays yours',
    privSub: 'Personal finance is personal. Floussi is built local-first, with no invented numbers and no data resale.',
    priv1t: 'Your own database',
    priv1d: 'Transactions live in your cloud (Turso) or local SQLite — with automatic backups before every sensitive action.',
    priv2t: 'Zero demo data',
    priv2d: 'The app starts empty. Every number you see comes from what you actually logged.',
    priv3t: 'Installable PWA',
    priv3d: 'Works offline for browsing, installs like a native app, respects your theme and language.',
    ctaTitle: 'Ready to see where your money goes?',
    ctaSub: 'Open FLOUSSI and get your financial score in seconds.',
    ctaButton: 'Open FLOUSSI',
    footerTag: 'AI money coach, made for Morocco.',
    footerTech: 'Built with',
    demoNote: 'The preview above shows your real account.',
  },
  fr: {
    navProduct: 'Produit',
    navIq: 'Floussi IQ',
    navCoach: 'Coach IA',
    navPrivacy: 'Confidentialité',
    openApp: 'Ouvrir FLOUSSI',
    badge: 'Coach financier IA · Maroc',
    h1a: 'Comprenez votre argent.',
    h1b: 'Prenez de meilleures décisions.',
    sub: 'FLOUSSI réunit vos transactions, analyse votre comportement financier et le transforme en repères clairs — avec un coach IA qui parle darija, français et anglais.',
    ctaPrimary: 'Essayer FLOUSSI',
    ctaSecondary: 'Voir le produit',
    liveLabel: 'En direct de votre compte',
    prevToday: 'Dépensé aujourd’hui',
    prevWeek: 'Cette semaine',
    prevMonth: 'Ce mois',
    prevRecent: 'Transactions récentes',
    prevScore: 'Floussi IQ',
    statTx: 'transactions suivies',
    statIq: 'intelligence financière',
    statLang: 'langues, RTL natif',
    statMAD: 'devise locale (MAD)',
    featTitle: 'Tout votre argent, au même endroit',
    featSub: 'Conçu pour dépenser comme au Maroc — cash, souk, famille, factures fixes.',
    feat1t: 'Transactions sans effort',
    feat1d: 'Notez une dépense en quelques secondes. Cherchez en langage naturel — « tnine 11 decembre », « khobze », « 50 dh » — dans les trois langues.',
    feat2t: 'Des analyses qui expliquent',
    feat2d: 'Où va votre argent, nécessaire vs évitable, habitudes du week-end, tendances de 14 jours à un an.',
    feat3t: 'Budgets & objectifs',
    feat3d: 'Plafonds mensuels par catégorie avec alertes intelligentes, et objectifs d’épargne avec progression réelle.',
    feat4t: 'Notifications utiles',
    feat4d: 'Alertes budget, dépenses inhabituelles, résumés hebdomadaires — générés depuis vos vraies données, pas des modèles.',
    feat5t: 'Floussi IQ',
    feat5d: 'Un score propriétaire 0–100 de votre santé financière, avec les facteurs exacts qui le composent.',
    feat6t: 'Installable & hors-ligne',
    feat6d: 'Une vraie PWA : ajoutez-la à votre écran d’accueil, vos données se synchronisent sur votre cloud.',
    iqTitle: 'Un score financier enfin lisible',
    iqSub: 'Floussi IQ lit votre comportement réel — rythme, essentiels, week-end, séries — et explique chaque point.',
    iqWhy: 'Ce qui fait bouger le score',
    iqCta: 'Ouvrir Floussi IQ',
    coachTitle: 'Un coach IA qui connaît vos chiffres',
    coachSub: 'Posez la question simplement — darija, français ou anglais. Les réponses sont calculées depuis vos vraies transactions, jamais inventées.',
    coachQ: 'Où ai-je le plus dépensé ce mois-ci ?',
    coachA1: 'Votre plus grosse catégorie ce mois est',
    coachA2: 'soit {pct}% de vos dépenses. Le rythme hebdo est bon — en réduire un peu économiserait environ',
    coachA3: 'ce mois-ci.',
    coachPerMonth: '/ mois',
    triTitle: 'Trois langues. Une vraie RTL.',
    triSub: 'Pas un simple miroir — la darija est pensée de première classe : mise en page, graphiques, formulaires et nombres se retournent correctement.',
    triEn: 'English',
    triFr: 'Français',
    triAry: 'الدارجة',
    privTitle: 'Vos données restent les vôtres',
    privSub: 'Les finances personnelles, c’est personnel. Floussi est local-first, sans chiffres inventés ni revente de données.',
    priv1t: 'Votre propre base',
    priv1d: 'Les transactions vivent dans votre cloud (Turso) ou SQLite local — avec sauvegardes automatiques avant chaque action sensible.',
    priv2t: 'Zéro donnée de démo',
    priv2d: 'L’app démarre vide. Chaque chiffre affiché vient de ce que vous avez réellement saisi.',
    priv3t: 'PWA installable',
    priv3d: 'Consultation hors-ligne, installation comme une app native, thème et langue respectés.',
    ctaTitle: 'Prêt à voir où va votre argent ?',
    ctaSub: 'Ouvrez FLOUSSI et obtenez votre score financier en quelques secondes.',
    ctaButton: 'Ouvrir FLOUSSI',
    footerTag: 'Coach financier IA, pensé pour le Maroc.',
    footerTech: 'Construit avec',
    demoNote: 'L’aperçu ci-dessus montre votre vrai compte.',
  },
  ary: {
    navProduct: 'المنتوج',
    navIq: 'فلوسي IQ',
    navCoach: 'الكوتش IA',
    navPrivacy: 'الخصوصية',
    openApp: 'حل فلوسي',
    badge: 'كوتش ديال الفلوس بالذكاء الاصطناعي · المغرب',
    h1a: 'فهم فلوسك.',
    h1b: 'دير قرارات أحسن.',
    sub: 'فلوسي كيجمع المصاريف ديالك، كيحلل كيفاش كتصرف، و كيديرها بيها واضحة — مع كوتش ذكاء اصطناعي كيهضر الدارجة و الفرنسية و الإنجليزية.',
    ctaPrimary: 'جرّب فلوسي',
    ctaSecondary: 'شوف المنتوج',
    liveLabel: 'مباشر من الحساب ديالك',
    prevToday: 'صرفت اليوم',
    prevWeek: 'هاد السيمانة',
    prevMonth: 'هاد الشهر',
    prevRecent: 'آخر المصاريف',
    prevScore: 'فلوسي IQ',
    statTx: 'عملية مسجلة',
    statIq: 'ذكاء مالي',
    statLang: 'لوغات، RTL أصلي',
    statMAD: 'العملة ديالنا (درهم)',
    featTitle: 'كلشي على فلوسك، فبلاصة وحدة',
    featSub: 'مصمم على حساب كيفاش كنصرفو بصح فالمغرب — كاش، السوق، العائلة، الفاتورات.',
    feat1t: 'مصاريف بلا تعب',
    feat1d: 'سجل مصروف فثواني. قلب بالكلام العادي — « tnine 11 decembre »، « خبزة »، « 50 dh » — بأي لوغة.',
    feat2t: 'تحاليل كتفهمك',
    feat2d: 'فين كيمشي فلوسك، ضروري ولا يمكن تجنبو، عادات الويكند، الاتجاهات من 14 يوم لعام كامل.',
    feat3t: 'ميزانية و أهداف',
    feat3d: 'سقف شهري لكل فئة مع تنبيهات ذكية، و أهداف التوفير مع تقدم حقيقي.',
    feat4t: 'تنبيهات مفيدة',
    feat4d: 'تنبيهات الميزانية، مصاريف غريبة، حصيلة السيمانة — من المعطيات الحقيقية ديالك، ماشي قوالب.',
    feat5t: 'فلوسي IQ',
    feat5d: 'نقطة من 0 لـ 100 على الصحة المالية ديالك، مع العوامل بالضبط اللي كيديروها.',
    feat6t: 'تتبث و تخدم بلا أنترنيت',
    feat6d: 'PWA حقيقية: زيدها فالشاشة ديالك، و المعطيات كتتزامن مع الكلاود ديالك.',
    iqTitle: 'نقطة مالية واضحة و مفسرة',
    iqSub: 'فلوسي IQ كيقرا السلوك الحقيقي ديالك — الوتيرة، الضروريات، الويكند، السلاسل — و كيشرح كل نقطة.',
    iqWhy: 'شنو كيأثر على النقطة',
    iqCta: 'حل فلوسي IQ',
    coachTitle: 'كوتش IA كيعرف الأرقام ديالك',
    coachSub: 'سول بالكلام العادي — دارجة، فرنسية ولا إنجليزية. الجواب كيتحسب من المصاريف الحقيقية ديالك، عمره كيتخترع.',
    coachQ: 'شنو أكبر قسم صرفت فيه هاد الشهر؟',
    coachA1: 'أكبر قسم فهاد الشهر هو',
    coachA2: 'يعني {pct}% ديال مصاريفك. وتيرة السيمانة مزيانة — إلا نقصتي شوية منها غادي توفر تقريبا',
    coachA3: 'هاد الشهر.',
    coachPerMonth: '/ شهر',
    triTitle: 'ثلاث لوغات. و RTL حقيقية.',
    triSub: 'ماشي غير قلب ديال CSS — الدارجة مصممة من الأول: التصميم، الرسوم، الفورموليرات و الأرقام كيتقلبو مزيان.',
    triEn: 'English',
    triFr: 'Français',
    triAry: 'الدارجة',
    privTitle: 'المعطيات ديالك كتبقى ديالك',
    privSub: 'الفلوس شخصية. فلوسي مصمم local-first، بلا أرقام مخترعة و بلا بيع ديال المعطيات.',
    priv1t: 'الداتابيز ديالك',
    priv1d: 'المصاريف كيعيشو فالكلاود ديالك (Turso) ولا SQLite محلي — مع بكاب أوتوماتيك قبل كل حاجة حساسة.',
    priv2t: 'حتى ديمو',
    priv2d: 'التطبيق كيبدا خاوي. كل رقم كتشوفو جا من اللي سجلتي بصح.',
    priv3t: 'PWA تتبث',
    priv3d: 'تخدم بلا أنترنيت، كتبث بحال التطبيقات، و كتحترم الثيم و اللوغة ديالك.',
    ctaTitle: 'واجد تشوف فين كيمشي فلوسك؟',
    ctaSub: 'حل فلوسي و خود النقطة ديالك فثواني.',
    ctaButton: 'حل فلوسي',
    footerTag: 'كوتش ديال الفلوس، مصمم للمغرب.',
    footerTech: 'مبني ب',
    demoNote: 'الأبيركو اللي لفوق كيبين الحساب الحقيقي ديالك.',
  },
}

export type LandingCopy = (typeof landingCopy)['en']
